### ISSUE TITLE
Can't build this application on my device

### ISSUE THREAD

**Issue by Ahmed--Kamal** [miyosuda/TensorFlowAndroidMNIST#4]
## I got these errors and exceptions when I try to run this application on my sony xperia t2 ultra device 

06-19 04:52:34.050 5731-5731/jp.narr.tensorflowmnist D/dalvikvm: Late-enabling CheckJNI
06-19 04:52:34.120 5731-5731/jp.narr.tensorflowmnist D/dalvikvm: Trying to load lib /data/app-lib/jp.narr.tensorflowmnist-1/libtensorflow_mnist.so 0x427336d0
06-19 04:52:34.140 5731-5731/jp.narr.tensorflowmnist E/dalvikvm: dlopen("/data/app-lib/jp.narr.tensorflowmnist-1/libtensorflow_mnist.so") failed: dlopen failed: cannot locate symbol "getpagesize" referenced by "libtensorflow_mnist.so"...
06-19 04:52:34.140 5731-5731/jp.narr.tensorflowmnist W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Ljp/narr/tensorflowmnist/DigitDetector;
06-19 04:52:34.140 5731-5731/jp.narr.tensorflowmnist D/AndroidRuntime: Shutting down VM
06-19 04:52:34.140 5731-5731/jp.narr.tensorflowmnist W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41b3ed88)
06-19 04:52:34.140 5731-5731/jp.narr.tensorflowmnist E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: jp.narr.tensorflowmnist, PID: 5731
                                                                       java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "getpagesize" referenced by "libtensorflow_mnist.so"...
                                                                           at java.lang.Runtime.loadLibrary(Runtime.java:364)
                                                                           at java.lang.System.loadLibrary(System.java:526)
                                                                           at jp.narr.tensorflowmnist.DigitDetector.<clinit>(DigitDetector.java:29)
                                                                           at jp.narr.tensorflowmnist.MainActivity.<init>(MainActivity.java:42)
                                                                           at java.lang.Class.newInstanceImpl(Native Method)
                                                                           at java.lang.Class.newInstance(Class.java:1208)
                                                                           at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2152)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2284)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:212)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5133)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
                                                                           at dalvik.system.NativeStart.main(Native Method)

---

I'm using android studio 2.1.2
Device: Sony xperia t2 ultra (Android 4.4.3, API 19)

**Comment by miyosuda** [comment]
@Ahmed--Kamal 
It seems that you have same error logs as written in
https://github.com/tensorflow/tensorflow/issues/419

I used to build .o and .lo files with TensorFlow r0.8 original AndroidDemo api_level=21 setting with Bazel. And after that I extracted .o and .lo files from "bazel-out" dir.

So I think to fix this problem, first we need to build original r0.8 AndroidDemo with api_level=19 setting in bazel WORKSPACE file.
